### ISSUE TITLE
SMART Launch

### ISSUE THREAD

**Issue by jjdestef3** [fhir-fli/fhir#10]
Hi,

Appreciate the work you've done. You mentioned wanting to implement the SMART launch sequence. Was the first use case from within an EHR or a separate app (mobile)? Looking at some of the OAuth Flutter packages it seems possible to get this working on a phone with the same code base. The web might be different and require an approach similar to the way the SMART sample app works with the index and app pages. Are you still interested in getting some help with this?

Thx

**Comment by Dokotela** [comment]
I'm happy other people are interested! But yes, I could definitely use some input for the SMART launch. If you want to help, a good place to start would probably be looking at this repo: https://github.com/Dokotela/fhir_at_rest. I've been trying to make it easier to do the FHIR queries and searches in a logical way. Most of the basic queries I had, and then I got to SMART. I was actually just looking at it yesterday, and because I had to add a flutter package for the auth stuff, I need to refactor it (because I had been using mirrors). So I'll probably work on that first, and if you wanted to start on SMART, that would be great! There are a few of us on a slack channel if you wanted to join too: https://join.slack.com/t/fhir-fli/shared_invite/zt-hudq8zn5-fgrw_NE~gj9MkwT8~oGwbA

**Comment by jjdestef3** [comment]
Hi Grey,

I’ll join the slack. I was looking to do a mobile app against Blue Button to start. That seems pretty straight forward as its not the typical FHIR flow but there are requirements around “pixie”. Maybe there would be different packages for different use cases: Blue Button, App launch, EHR launch.

Thx

Thanks

**Comment by Dokotela** [comment]
That would be perfect. One of the guys in our group actually brought up the Blue Button yesterday.

**Comment by Dokotela** [comment]
I suppose another option would be to have all of the searches/queries in one package, and then another package that would handle the launches/authentication.

**Comment by Dokotela** [comment]
So I've done the latter, with the help of [drcdev](https://github.com/drcdev) and created a [restful package](https://github.com/fhir-fli/fhir_at_rest) and a second one for (smart authorization)[https://github.com/Dokotela/smart_on_fhir], although there are still some kinks to workout on that one.
