### ISSUE TITLE
Convenient access to dates / times

### ISSUE THREAD

**Issue by tiloc** [fhir-fli/fhir#13]
Hello,

I am using your package quite extensively and like it a lot. I find access to DateTime inconvenient, but could be missing something. I am looking for a getter/property that will return either null or a DateTime for a FhirDateTime. Instead I seem to get a rather inconvenient Either<PrimitiveFailure, DateTime> construct back.
This is leading to constructs like this one:
DateFormat.yMd(languageCode).add_jm().format(
                _observation.effectiveDateTime.value.getOrElse(() => null))

Is there an existing accessor like the one that I am looking for and I am simply overlooking it? Or could something like that be added to FhirDateTime?

Sincerely,
Tilo

**Comment by Dokotela** [comment]
I'm glad it's been working for you, and I appreciate the feedback! (it helps me to fine tune the package). So I created the primitives like that because it gave them automatic validation to ensure their format is correct ([as specified here](https://www.hl7.org/fhir/datatypes.html)). And I do think that's really important, but it does at times make it harder to work with. You can try calling toJson() or toString() (they should produce the same values for DateTimes). But I agree it could probably be easier to work with, so I may need to look into other ways to do the validation. DateTimes in general are tough to work with because in FHIR they can be just a year, a year/month, a year/month/day, a year/month/day/sec, etc. 

What do you think would work better for what you're trying to do? If you could just call _observation.effectiveDateTime.value would that be reasonable? Also, you're welcome to join our slack channel if you'd like: https://join.slack.com/t/fhir-fli/shared_invite/zt-kv1z4ahy-WbFYPh6Bn8YXN5cuscvS~g

**Comment by Dokotela** [comment]
Also, what are you using the package for? (I'm interested in use cases)

**Comment by tiloc** [comment]
I am using the package for mobile data capture. I am using various data sources (this one: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/health and a commercial Bluetooth library) to read sensors. Then I normalize everything into FHIR Observations, store them into a local database (currently Hive) and then sync them to a FHIR server.
So I have written a bunch of Widgets to display observations and some persistence code for them (just as JSON strings).

Based on this use case my date/times are always filled with year/month/date hour/minute/seconds and I don't need much in the ways of validation or handling of different precisions.

**Comment by Dokotela** [comment]
Alright, give it a whirl now. In version 0.2.2 I've slightly refactored how I work with primitives. You should just be able to call _observation.effectiveDateTime or _observation.effectiveDateTime.value and have it return the actual value. Because of this, I have to override '==' for all of those objects. So if you're trying to compare them with something else, they have to be called first.
```
final _id = Id('id');
final anotherId = 'id';
_id == anotherId; //true
anotherId == _id; //false
```
How do you like working with Hive? It looked good, but then I saw that he was deprecating it for a second version, so I didn't look too far into it yet.

**Comment by tiloc** [comment]
Hey thanks for listening! I will give this a whirl and it really looks much easier now.

I can't really tell yet, how much I like Hive, as I haven't used it for long. I am not asking much of a database, as I am merely using it to cache JSON strings and a couple of state flags (isSynched, synchAttemptCount, etc.). I tried Moor first, ditched it, now I am using Hive (also aware of the discontinuation). I am looking at Sembast (how is it working for you?) and maybe Isar (the successor to Hive, but still Alpha).
I am overall a bit unhappy about the state of affairs with databases in Flutter. I want to share a database between a background process and my app and it seems that all DBs under Flutter come with severe limitations when it comes to multi-isolate or multi-process. They all warn of corruption and lockups. So maybe I'll end up writing solid SqlLite code in my native portion and access it from a MethodChannel.

**Comment by tiloc** [comment]
I am trying out 0.2.2 now and it seems it is converting FhirDateTime to an ISO8601 String when you access .value on it?
All the other primitives are coming back as the similar Dart type, such as Integer.
But FhirDateTime does this:
```
String get value => _value.fold(
        (l) => l,
        (r) => _formattedFhirDateTime(r),
      );

```
all the other primitives are just doing `(r) => r`

any particular reason? I would find it more natural if .value returned a DateTime and .toString() would return a string.
My use-case is to pass the date/time into localized formatting methods for display, so losing access to the DateTime object would mean I have to re-parse the ISO8601 string into a DateTime before formatting it. getOrElse was able to return the DateTime.

**Comment by Dokotela** [comment]
Yeah, so this is one of those idiosyncrasies with FHIR. FhirDateTime only requires a year. So any of the following are valid:
```
FhirDateTime('2020')
FhirDateTime('2020-01')
FhirDateTime('2020-01-01')
```
And then when converted back, they should only have the values given.
```
print(FhirDateTime('2020')); // '2020'
print(FhirDateTime('2020-01')); // '2020-01'
print(FhirDateTime('2020-01-01')); // '2020-01-01'
```
But if I call them a DateTime in Dart, I get the following:
```
print(DateTime(2020)); // '2020-01-01 00:00:00.000'
print(DateTime(2020, 01)); // '2020-01-01 00:00:00.000'
print(DateTime(2020, 01, 01)); // '2020-01-01 00:00:00.000'
```
Which isn't correct. So that's why I do the formatting before I return the value. The three classes that work like this are:
https://github.com/MayJuun/fhir/blob/dev/fhir/lib/primitive_types/date.dart
https://github.com/MayJuun/fhir/blob/dev/fhir/lib/primitive_types/fhir_date_time.dart
https://github.com/MayJuun/fhir/blob/dev/fhir/lib/primitive_types/instant.dart

Feel free to take a look and if you think there's a better way of ensuring the proper value is returned, I'm happy to accept pull-requests.

I will consider returning a DateTime when .value is called though.

The one other option, I suppose, would be to add a .dateTime method to those classes. So 
_observation.effectiveDateTime.value or _observation.effectiveDateTime, will continue to work as they do now.

But
_observation.effectiveDateTime.dateTime would return DateTime.tryParse(value)

**Comment by tiloc** [comment]
I am putting on my Medical Informatics hat and pondering this :-)
I like your idea of either having .value or .dateTime return a real Dart DateTime. I guess I usually use dates to format them, feed them into a calendar, sort them etc. rather than process them as a string. I am wondering whether a "precision" property would be the best of both worlds.
So that
```
print(FhirDateTime('2020-01')); // '2020-01'
print(FhirDateTime('2020-01').value); // '2020-01-01 00:00:00.000'
print(FhirDateTime('2020-01').precision == DateTimePrecision.YYMM);  // true
```
According to the spec there can be 4 levels of precision.

FWIW: As per the spec 'Instant' is always full precision, so I guess it could always simply be a DateTime.

**Comment by tiloc** [comment]
Working on the idea: https://github.com/tiloc/fhir/commit/f9a67e0e7e8c2829fd05a1b63f32d2a95b33b385
Not enough test coverage yet, but shouldn't break more things than your previous change, handle string, DateTime, precision, and be ready for a PR before the weekend.

**Comment by Dokotela** [comment]
Thanks again for the PR, should be all incorporated in 0.2.4.
